<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311165342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CAD560E5F37A13B ON api_tokens (token)');
        $this->addSql('CREATE INDEX IDX_2CAD560EA76ED395 ON api_tokens (user_id)');
        $this->addSql('CREATE INDEX idx_api_token ON api_tokens (token)');
        $this->addSql('ALTER TABLE api_tokens ADD CONSTRAINT FK_2CAD560EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contexts ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE contexts ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE contexts ALTER sort_order DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN contexts.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN contexts.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_contexts_owner RENAME TO IDX_AC51CEB57E3C61F9');
        $this->addSql('ALTER INDEX idx_context_tags_context RENAME TO IDX_A6D0D0176B00C1CF');
        $this->addSql('ALTER INDEX idx_context_tags_tag RENAME TO IDX_A6D0D017BAD26311');
        $this->addSql('ALTER TABLE projects ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE projects ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN projects.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN projects.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_projects_owner RENAME TO IDX_5C93B3A47E3C61F9');
        $this->addSql('ALTER TABLE prompt_compositions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE prompt_compositions ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE prompt_compositions ALTER context_titles DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN prompt_compositions.created_at IS \'\'');
        $this->addSql('ALTER TABLE prompt_templates ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE prompt_templates ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN prompt_templates.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN prompt_templates.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_templates_owner RENAME TO IDX_A51E06EE7E3C61F9');
        $this->addSql('ALTER INDEX idx_pt_tags_template RENAME TO IDX_2B5D7422A7F0069D');
        $this->addSql('ALTER INDEX idx_pt_tags_tag RENAME TO IDX_2B5D7422BAD26311');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT reset_password_request_user_id_fkey');
        $this->addSql('ALTER TABLE reset_password_request ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reset_password_request ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'\'');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_reset_pwd_user RENAME TO IDX_7CE748AA76ED395');
        $this->addSql('ALTER TABLE snippets ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE snippets ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN snippets.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN snippets.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_snippet_owner RENAME TO IDX_ED21F5DC7E3C61F9');
        $this->addSql('ALTER TABLE tags ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tags ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN tags.created_at IS \'\'');
        $this->addSql('ALTER INDEX tags_name_key RENAME TO UNIQ_6FBC94265E237E06');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER roles DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER is_verified DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_tokens DROP CONSTRAINT FK_2CAD560EA76ED395');
        $this->addSql('DROP TABLE api_tokens');
        $this->addSql('ALTER INDEX idx_a6d0d017bad26311 RENAME TO idx_context_tags_tag');
        $this->addSql('ALTER INDEX idx_a6d0d0176b00c1cf RENAME TO idx_context_tags_context');
        $this->addSql('ALTER TABLE contexts ALTER id SET DEFAULT nextval(\'contexts_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE contexts ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE contexts ALTER sort_order SET DEFAULT 0');
        $this->addSql('COMMENT ON COLUMN contexts.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN contexts.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_ac51ceb57e3c61f9 RENAME TO idx_contexts_owner');
        $this->addSql('ALTER TABLE projects ALTER id SET DEFAULT nextval(\'projects_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE projects ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN projects.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN projects.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_5c93b3a47e3c61f9 RENAME TO idx_projects_owner');
        $this->addSql('ALTER TABLE prompt_compositions ALTER id SET DEFAULT nextval(\'prompt_compositions_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE prompt_compositions ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE prompt_compositions ALTER context_titles SET DEFAULT \'[]\'');
        $this->addSql('COMMENT ON COLUMN prompt_compositions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_2b5d7422a7f0069d RENAME TO idx_pt_tags_template');
        $this->addSql('ALTER INDEX idx_2b5d7422bad26311 RENAME TO idx_pt_tags_tag');
        $this->addSql('ALTER TABLE prompt_templates ALTER id SET DEFAULT nextval(\'prompt_templates_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE prompt_templates ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN prompt_templates.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN prompt_templates.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_a51e06ee7e3c61f9 RENAME TO idx_templates_owner');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE reset_password_request ALTER id SET DEFAULT nextval(\'reset_password_request_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reset_password_request ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT reset_password_request_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_7ce748aa76ed395 RENAME TO idx_reset_pwd_user');
        $this->addSql('ALTER TABLE snippets ALTER id SET DEFAULT nextval(\'snippets_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE snippets ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN snippets.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN snippets.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_ed21f5dc7e3c61f9 RENAME TO idx_snippet_owner');
        $this->addSql('ALTER TABLE tags ALTER id SET DEFAULT nextval(\'tags_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tags ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN tags.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_6fbc94265e237e06 RENAME TO tags_name_key');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER roles SET DEFAULT \'["ROLE_USER"]\'');
        $this->addSql('ALTER TABLE users ALTER is_verified SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
